// Borland C++ Windows - (C) Copyright 1992 by Borland International

// FILE : cmdlgr.h

#define szCMDLGAPAbout "Common Dialog Example\nCopyright (c) 1992 Borland International, Inc."

#define CM_U_FILEOPEN               0x100
#define CM_EXIT                     0x101
#define CM_U_EDITCUT                0x201
#define CM_U_EDITCOPY               0x202
#define CM_U_EDITPASTE              0x203

#define CM_U_HELPABOUT              0x300
